language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8

before_install:
  - cd $HOME
  - rm -rf kotlin
  - wget -c -O kotlin.zip https://github.com/JetBrains/kotlin/releases/download/v1.1.51/kotlin-compiler-1.1.51.zip
  - unzip kotlin.zip
  - mv kotlinc kotlin

env:
  - KOTLIN_HOME=$HOME/kotlin/

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir src/test/resources/out
  - mkdir src/test/resources/benchmark_out